### ISSUE TITLE
Usage with external webpack.config file

### ISSUE THREAD

**Issue by mdocter** [xabikos/aspnet-webpack#1]
Hi,

Thanks for creating this great tool.
I'm trying to get it to work with an external webpack.config file, so my `Startup.cs` file contains the following:

`app.UseWebpack("webpack/webpack.config.js", "bundle.js", new WebpackDevServerOptions("localhost", 50001));`

Now I'm trying to figure out what exactly should be present in this  `webpack/webpack.config.js` file to get it running...
I tried the following, but didn't get it to work:

``` js
'use strict';
var fs = require('fs');
var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

var commonLoaders = [
  { test: /.*\.json$/, loader: 'json' },
  { test: /.*\.md$/, loader: 'file' },
  { test: /.*\.css$/, loader: 'css-loader' },
  { test: /.*\.(sass|scss)$/, loaders: ["style", "css", "sass"] },
  { test: /.*\.jsx?$/, loaders: ['react-hot', 'babel?presets[]=react,presets[]=es2015'], exclude: /node_modules/ },
  { test: /.*\.(gif|png|jpg)$/, loaders: ['file?hash=sha512&digest=hex&size=16&name=[hash].[ext]', 'image-webpack-loader?optimizationLevel=7&interlaced=false'] },
  { test: /.*\.(eot|woff|ttf|svg)$/, loader: 'file?hash=sha512&digest=hex&size=16&name=cd [hash].[ext]' }
];
var assetsPath = path.join(__dirname, '..', 'wwwroot');
var publicPath = assetsPath;
var extensions = ['', '.js', '.jsx', '.styl'];

module.exports = {
    entry: [
        'webpack-dev-server/client?http://localhost:50001', // WebpackDevServer host and port
        'webpack/hot/only-dev-server', // "only" prevents reload on syntax errors
        './app/index'
    ],
    output: {
        path: assetsPath,
        publicPath: publicPath,
        filename: 'bundle.js'
    },
    resolve: {
        extensions: extensions
    },
    module: {
        loaders: commonLoaders
    },
    plugins: [
        function () {
            this.plugin('done', function (stats) {
                fs.writeFileSync(path.join(__dirname, 'stats.generated.json'), JSON.stringify(stats.toJson()));
            });
        },
        new ExtractTextPlugin('style.[contenthash].css', {
            allChunks: true
        }),
        new webpack.HotModuleReplacementPlugin()
    ]
};
```

Can you point me in the right direction please? There seems to be nothing listening on port 50001, so my `bundle.js` doesn't get served from the webpack dev server.

**Comment by xabikos** [comment]
How did you come up with this complex config file? Are you sure you need all that loaders? I would suggest to start with a simple configuration file in order to understand what is happening and then try to move to more advanced configuration. Did you try to execute the samples and faced some issues? Maybe you could use that as starting point. In any case I am here for some further help.

**Comment by mdocter** [comment]
Your samples don't demonstrate how to use an external webpack.config.js file. 
So in my case they can't be used. The number of loaders in my example config is irrelevant. It's the configuration of the webpack-dev-server combined with the hot reloading where the issue is.
Please copy your `AspnetReact.Webpack` example project as a third one and make it work with an external webpack.config.js file located in the webpack subfolder.

**Comment by xabikos** [comment]
@mdocter I just modified the react sample to include an example with external configuration file. Could you take a look and give some feedback?

**Comment by mdocter** [comment]
Hi @xabikos, 

I did a fresh clone and tried it out, but it doesn't work.
It can't find the `node_modules\.bin\*.cmd` files. The `GetNodeExecutable(toolToExecute)` method  thinks that the `node_modules` folder is in the `wwwroot` folder, but it should be one level up. That's because the `Directory.GetCurrentDirectory()` returns the path to the `wwwroot` folder.
So if that's the way it's working than probably the `Startup.cs` line 45:

`app.UseWebpack("webpack_external/webpack.config.js", "bundle.js", new WebpackDevServerOptions());`

should probably be changed to:

`app.UseWebpack("../../webpack_external/webpack.config.js", "bundle.js", new WebpackDevServerOptions());`

because this config file path is added as arguments `--config webpack_external/webpack.config.js` to `AspnetReact.Webpack\node_modules\.bin\webpack-dev-server.cmd`.

**Comment by xabikos** [comment]
Are you using IIS express or Kestrel? Because IIS express is not supported and from what you are describing I think this is the problem

**Comment by mdocter** [comment]
Yep, that was definitely the case :-) 
Now it's working great! Thank you so much for this nice example!
