### ISSUE TITLE
Execute does not setup properly setup hot reloading

### ISSUE THREAD

**Issue by cgatian** [xabikos/aspnet-webpack#15]
The method startup with the following signature
`
 Execute(string configFile, string outputFileName, WebpackDevServerOptions devServerOptions)`

Does not supply the correct arguments to  webpack-dev-server to enable hot reloading.  Other methods invoke GetWebpackArguments to properly append the Hot Reload arguments

![image](https://cloud.githubusercontent.com/assets/1752170/13726931/ec980244-e8aa-11e5-8c10-17b2e2ad3b6d.png)

**Comment by xabikos** [comment]
Ok probably the documentation is not clear enough regarding this. When you use the [UseWebpack](https://github.com/xabikos/aspnet-webpack/blob/master/src/Webpack/WebpackExtenstions.cs#L64) extension method and pass as an argument a configuration file then it's up to you to set up the hot reloading in that configuration file. You need to supply the dev server option, that should be the same as in the external configuration file, to that method in order the middleware to inject the correct script tag into the html file. Is it more clear now?

[Here](https://github.com/xabikos/aspnet-webpack/blob/master/samples/AspnetReact.Webpack/webpack_external/webpack.config.js) you can see an example configuration file that has hot reloading enabled. 

Please let me know if this helps you.

**Comment by cgatian** [comment]
I think we can make this better. Since the we can read the config we can bypass a lot of steps for the end user.

**Comment by xabikos** [comment]
I agree and tried to read and parse a webpack config file but it's relatively hard as there are too many combinations. My idea is to provide transparency to the user for webpack configuration in order to have an easy beginning but after a certain point and especially for complex and advance scenario an external configuration file is required I think.

**Comment by cgatian** [comment]
I didn't know that would work because I think the documentation says the "hot" property isn't vaild? I'm new to this and probably just wrong, for some reason I didn't think you could specify "hot inline" through a config.

**Comment by cgatian** [comment]
Wow looking back I see how tot do it correctly. Sorry about that I just have a bad config.
