### ISSUE TITLE
IFileProvider - embedded files

### ISSUE THREAD

**Issue by dazinator** [xabikos/aspnet-webpack#22]
Quick question really,

If my application has embedded files (.js files etc) accessed via an `EmbeddedFileProvider` - can webpack seem them? I'm assuming it cannot and that the files must be present on the physical file system - is that correct?

**Comment by xabikos** [comment]
Hello @dazinator and sorry for my late reply.

As you assumed webpack can't access these files. As far as I know the file needs to be a physical one in the file system.

**Comment by dazinator** [comment]
No worries, thank you for confirming ;-)
