### ISSUE TITLE
How could I combine ASP.NET Core with AngularClass/angular2-webpack-starter?

### ISSUE THREAD

**Issue by RobertPaulson90** [xabikos/aspnet-webpack#26]
I'm a fan of the [AngularClass/angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) boilerplate. It is a very good foundation for starting an Angular project (they use webpack too). Has best practices, karma-jasmine, perhaps too opinionated, but a very good foundation with a solid backing community imo.

I really want to achieve a fusion of both asp.net core and that boilerplate, but am pretty lost. Could anyone give some tips on how I could achieve such an environment? 

I imagine this repo is the closest chance to getting help on the dilemma, out there on the internet. Without being experienced in both technologies already.

**Comment by xabikos** [comment]
Hello @amivit there is certainly an option to combine the starter kit with an asp.net core application and use the webpack nuget package but it's not something really trivial. One of my priorities is to provide an Angular 2 sample with webpack and after that it should be more easily to change it to use the starter kit.

**Comment by RobertPaulson90** [comment]
Sounds very cool. Will be exciting to see. You can maybe get some inspiration here, because in the meantime I discovered [this yeoman generator](http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/) developed by Stevens Anderson, which is capable of setting up an Angular 2 + webpack + .net core environment. 

I have been trying to learn from his implementation, to adapt it to the AngularClass starter-kit, but without much success (I really prefer their opinionated boilerplate). I am still in the early learning phase of becoming a developer, I'm just too excited with all the bleeding edge technology, when in reality, I should be more focused on just studying. I will follow you to see if anything new & shiny for me try out :)
