### ISSUE TITLE
Cannot specify hot-load and configFile simultaneously 

### ISSUE THREAD

**Issue by 0xn3bs** [xabikos/aspnet-webpack#27]
I have the following code 

```
if (env.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
    app.UseWebpack("webpack.config.js", "js/app.js", new WebpackDevServerOptions("localhost", 8080));
}
```

However, when I launch my app I get the following output:

> info: webpack-dev-server[0]
>       webpack-dev-server is called with these arguments: --config webpack.config.js

How do I enable --inline and --hot as additional command-line arguments while still using my webpack config?

**Comment by xabikos** [comment]
In this way of configuration you have an external file, the webpack.config.js, and you should be able to configure the --inline and --hot arguments in there. This is done normally in the section devserver of the config file. Have a look on [this](https://github.com/xabikos/aspnet-webpack/blob/master/samples/AspnetReact.Webpack/webpack_external/webpack.config.js#L38) configuration file on the samples. Please let me know if you need additional info.

**Comment by 0xn3bs** [comment]
@xabikos thanks a lot for linking that example because WebPack's documentation on devServer is [super sparse](https://webpack.github.io/docs/configuration.html#devserver).

I was able to get it working :)
