### ISSUE TITLE
Cant get samples to run

### ISSUE THREAD

**Issue by jdosullivan** [xabikos/aspnet-webpack#29]
Ran restore, build and then run. I got a the navbar header with a blank screen. This is from the ReactWebpack sample. 

Does anyone have a step by step walkthrough as to see this working?
I am tired of debugging webpack on every platform.

Sorry for the rant.

Not really :(

**Comment by xabikos** [comment]
Hello @jahmaiosullivan 
I guess you managed to execute the samples as long as you closed this issue.

**Comment by jdosullivan** [comment]
I did but I forgot what I did at the time. Thanks again.
