### ISSUE TITLE
Port 8080 to Port 5000 Mapping not working

### ISSUE THREAD

**Issue by harsimranb** [xabikos/aspnet-webpack#31]
I have everything setup as per the documentation.  My bundle is getting generated, and I can access it here:
http://localhost:8080/bundle.js
However, it does not work here:
http://localhost:5000/bundle.js

This is my code:

```
app.UseDeveloperExceptionPage();
app.UseWebpack(
    "webpack.config.js",
    "dist/builder.js",
    new WebpackDevServerOptions("localhost", 5000));
```

This is my webpack: https://gist.github.com/harsimranb/7f29e8156ce633eb207741e5162be0f8

Any thoughts?

**Comment by paqogomez** [comment]
Your configuration seems similar to mine.  The thing to understand is that you must use 2 webservers.  One on 5000, one on 8080.  5000 serves up your CSHTML.  8080 serves your Angular.

Webpack should inject references to the 8080 host into your html, so you dont have to.

**Comment by harsimranb** [comment]
Thank you, I figured it out. I did not realize that webpack was dynamically serving the bundled scripts from a different server.  Thanks.

**Comment by paqogomez** [comment]
That was a hard one for me to figure out too.  Close this issue if you've got it resolved.  Good Luck!

**Comment by xabikos** [comment]
As far as I understand is not clear that actually two web servers exist with this set up, so I will try to update the documentation to avoid similar cases in the future.

**Comment by harsimranb** [comment]
Closed this issue.  In the code `new WebpackDevServerOptions("localhost", PORT)`, the PORT has to be the port specified in the webpack config to dynamically serve the bundled scripts.  The way hot reload works is that Webpack listens to script changes and dynamically updates the script on the fly.  All this is handled by node and webpack on a different port, which is defined in the webpack config file: 

```
devServer: {
        host: "0.0.0.0",
        port: "4000",
        colors: true,
        historyApiFallback: true,
        hot: true,
        inline: true,
        stats: 'errors-only'
    }
```

If anyone has more questions, I can provide an example.

**Comment by xabikos** [comment]
Perfect explanation @harsimranb Thank you a lot!

**Comment by paqogomez** [comment]
For me, webpack IS listening for script changes and dynamically CREATES the
script, but the browser does not update the changes.

I've set my external webpack config file with these settings with the same
result.  The only exception is that when i include "inline: true" I get an
error in my page that says that "require is not defined."

Any ideas on how to make the hot module loading work?

**Comment by harsimranb** [comment]
The issue might be with in Webpack middleware.  In the Startup.cs file of your Asp.Net Core project, make sure you have `services.AddWebpack();` in the `ConfigureServices(IServiceCollection services)` method.

Next, in the `Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)` method, you should have the following:

```
if (env.IsDevelopment())
{
     app.UseWebpack("webpack.config.js", "Bundle.js", new WebpackDevServerOptions());
     //...
}
```

The default parameters for WebpackDevServerOptions are `WebpackDevServerOptions(string host = "localhost", int port = 4000)`.  If you are serving from a different port, make sure you specify that port in the WebpackDevServerOptions constructor. 

Let me know if this solves your problem.

**Comment by paqogomez** [comment]
My middleware is working well, I have done all those things.

The port that I'm using is 8080 for the scripts.
If I change something , it says "webpack: bundle is invalid", then promptly
builds the bundle again until it says "webpack: bundle is valid".

But the webpage (localhost:5000) doesnt change.

**Comment by xabikos** [comment]
@paqogomez in hour case you have an Angular 1.x version, right? In this case if you change a piece of JavaScript doesn't refresh the page automatically? Could you compare with the corresponding [sample](https://github.com/xabikos/aspnet-webpack/tree/master/samples/AspnetAngular1.Webpack) in this repository?

**Comment by paqogomez** [comment]
@xabikos  I'm using Angular 2, and I've found the problem, though I dont know how to solve it. 

When I add the 'inline: true' flag in the DevServer portion of my webpack.config.js it does something to my script files.  The error I get when I load a page is: `require is not defined`.  When i take off the inline flag, everything loads fine, but i get no hot loading.
